baseURL = "https://agungdh.com"
title = "AgungDH"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2021-{year} AgungDH. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# Pagination
paginate = 5
# paginatePath = "page"

# Disqus
disqusShortname = "agungdh"

# Google analytics
googleAnalytics = "G-LX7KWMZK7T"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

# [blackfriday]
#   hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
